spring:
  profiles:
    active: secret
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: # mysql url
    username: # mysql username
    password: # mysql password
  jpa:
    hibernate:
      ddl-auto: create